/*
 * The MIT License (MIT)
 * Copyright (c) 2016 Jim Liu
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.jim.mapper;

import com.jim.model.ArticlesMetadata;

public interface ArticlesMetadataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles_metadata
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles_metadata
     *
     * @mbggenerated
     */
    int insert(ArticlesMetadata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles_metadata
     *
     * @mbggenerated
     */
    int insertSelective(ArticlesMetadata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles_metadata
     *
     * @mbggenerated
     */
    ArticlesMetadata selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles_metadata
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ArticlesMetadata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles_metadata
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ArticlesMetadata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles_metadata
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ArticlesMetadata record);
}