package com.jim.mapper;

import com.jim.model.ArticlesMetadata;

public interface ArticlesMetadataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles_metadata
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles_metadata
     *
     * @mbggenerated
     */
    int insert(ArticlesMetadata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles_metadata
     *
     * @mbggenerated
     */
    int insertSelective(ArticlesMetadata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles_metadata
     *
     * @mbggenerated
     */
    ArticlesMetadata selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles_metadata
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ArticlesMetadata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles_metadata
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ArticlesMetadata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles_metadata
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ArticlesMetadata record);
}