package com.jim.mapper;

import com.jim.model.CommentsMetadata;

public interface CommentsMetadataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments_metadata
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments_metadata
     *
     * @mbggenerated
     */
    int insert(CommentsMetadata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments_metadata
     *
     * @mbggenerated
     */
    int insertSelective(CommentsMetadata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments_metadata
     *
     * @mbggenerated
     */
    CommentsMetadata selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments_metadata
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CommentsMetadata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments_metadata
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(CommentsMetadata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments_metadata
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CommentsMetadata record);
}