package com.jim.model;

import java.util.Date;

import java.io.Serializable;
import java.util.Date;

public class Article implements Serializable {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.userId
     *
     * @mbggenerated
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.create_at
     *
     * @mbggenerated
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.update_at
     *
     * @mbggenerated
     */
    private Date updateAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.isDraft
     *
     * @mbggenerated
     */
    private Boolean isdraft;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.isPrivate
     *
     * @mbggenerated
     */
    private Boolean isprivate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.id
     *
     * @return the value of articles.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.id
     *
     * @param id the value for articles.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.title
     *
     * @return the value of articles.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.title
     *
     * @param title the value for articles.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.userId
     *
     * @return the value of articles.userId
     *
     * @mbggenerated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.userId
     *
     * @param userid the value for articles.userId
     *
     * @mbggenerated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.create_at
     *
     * @return the value of articles.create_at
     *
     * @mbggenerated
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.create_at
     *
     * @param createAt the value for articles.create_at
     *
     * @mbggenerated
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.update_at
     *
     * @return the value of articles.update_at
     *
     * @mbggenerated
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.update_at
     *
     * @param updateAt the value for articles.update_at
     *
     * @mbggenerated
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.isDraft
     *
     * @return the value of articles.isDraft
     *
     * @mbggenerated
     */
    public Boolean getIsdraft() {
        return isdraft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.isDraft
     *
     * @param isdraft the value for articles.isDraft
     *
     * @mbggenerated
     */
    public void setIsdraft(Boolean isdraft) {
        this.isdraft = isdraft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.isPrivate
     *
     * @return the value of articles.isPrivate
     *
     * @mbggenerated
     */
    public Boolean getIsprivate() {
        return isprivate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.isPrivate
     *
     * @param isprivate the value for articles.isPrivate
     *
     * @mbggenerated
     */
    public void setIsprivate(Boolean isprivate) {
        this.isprivate = isprivate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.content
     *
     * @return the value of articles.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.content
     *
     * @param content the value for articles.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}