package com.jim.model;

public class CommentsMetadata {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments_metadata.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments_metadata.commentId
     *
     * @mbggenerated
     */
    private Long commentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments_metadata.key
     *
     * @mbggenerated
     */
    private String key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments_metadata.value
     *
     * @mbggenerated
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments_metadata.id
     *
     * @return the value of comments_metadata.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments_metadata.id
     *
     * @param id the value for comments_metadata.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments_metadata.commentId
     *
     * @return the value of comments_metadata.commentId
     *
     * @mbggenerated
     */
    public Long getCommentid() {
        return commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments_metadata.commentId
     *
     * @param commentid the value for comments_metadata.commentId
     *
     * @mbggenerated
     */
    public void setCommentid(Long commentid) {
        this.commentid = commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments_metadata.key
     *
     * @return the value of comments_metadata.key
     *
     * @mbggenerated
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments_metadata.key
     *
     * @param key the value for comments_metadata.key
     *
     * @mbggenerated
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments_metadata.value
     *
     * @return the value of comments_metadata.value
     *
     * @mbggenerated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments_metadata.value
     *
     * @param value the value for comments_metadata.value
     *
     * @mbggenerated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }
}